on:
  workflow_call:
    inputs:
      ecr_password:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 714943446733.dkr.ecr.us-east-1.amazonaws.com/gh-workflows
      credentials:
        username: AWS
        password: ${ECR_PASSWORD}
